### ISSUE TITLE
How To Setup Local Client and Photon Server

### ISSUE THREAD

**Issue by chrisjd20** [JaydeeAlkema/ProjectZ#1]
Was hoping to checkout your game. 

Do I go to scenes -> Rooms to run client? Then do run and build?

Also

How do I setup a local photon server myself for your game?

Theres no documentation so I'm a little lost. Havent done much with Unity myself. 

Any help is much appreciated, thanks!

**Comment by chrisjd20** [comment]
![image](https://user-images.githubusercontent.com/11812223/79883252-ad70d080-83c1-11ea-8a7e-d0850c421a31.png)
 Found the server setting. Not sure how to configure this to connect to a server. 

How do I run a server for this game?

**Comment by chrisjd20** [comment]
Do I need to create a Photon server say using something like this:

https://github.com/rossknudsen/PhotonServerDocker

**Comment by JaydeeAlkema** [comment]
Hey man, Thanks for showing interest in this project. Unfortunately,
I haven't done anything special yet for people to start using this project.
But if you're interested, I followed the Photon Engine 2 guide from First
Gear Games. Here's the link:
https://www.youtube.com/playlist?list=PLkx8oFug638oMagBH2qj1fXOkvBr6nhzt

I will be starting to work on this project soon hopefully.

**Comment by chrisjd20** [comment]
Hey thanks! Actually I just figured that out about your game and about how to use photon. Thanks.
